# Silent Boot Configuration
echo -e "## Silent Boot Configuration"
echo -e "1. \033[1mEdit Kernel Command Line\033[0m"
echo -e "   - Append the following to /etc/kernel/cmdline:"
echo -e "     \033[3mquiet splash loglevel=3 vt.global_cursor_default=0 plymouth.ignore-serial-consoles\033[0m"
echo -e "   - Example:"
echo -e "     \033[3mroot=PARTUUID=xxxx-xxxx-xxxx-xxxx rw quiet splash loglevel=3 vt.global_cursor_default=0 plymouth.ignore-serial-consoles\033[0m"
echo -e "   - To determine the PARTUUID, run:"
echo -e "     \033[3mblkid\033[0m"
echo -e "2. \033[1mReinstall the Kernel\033[0m"
echo -e "   - Run:"
echo -e "     \033[3msudo pacman -S linux\033[0m\n"

# Plymouth Splash Screen Setup
echo -e "## Plymouth Splash Screen Setup"
echo -e "1. \033[1mInstall Plymouth\033[0m"
echo -e "   - Run:"
echo -e "     \033[3msudo pacman -S plymouth\033[0m"
echo -e "2. \033[1mModify mkinitcpio Configuration\033[0m"
echo -e "   - Open /etc/mkinitcpio.conf:"
echo -e "     \033[3msudo nano /etc/mkinitcpio.conf\033[0m"
echo -e "   - Add 'plymouth' before 'filesystems' in the HOOKS line:"
echo -e "     \033[3mHOOKS=(base udev autodetect modconf block plymouth filesystems keyboard fsck)\033[0m"
echo -e "3. \033[1mRegenerate Initramfs\033[0m"
echo -e "   - Run:"
echo -e "     \033[3msudo mkinitcpio -P\033[0m"
echo -e "4. \033[1mSet Plymouth Theme\033[0m"
echo -e "   - Set theme to 'bgrt' (or your preferred theme):"
echo -e "     \033[3msudo plymouth-set-default-theme -R bgrt\033[0m"
echo -e "5. \033[1mEnable Plymouth Service at Boot\033[0m"
echo -e "   - Run:"
echo -e "     \033[3msudo systemctl enable plymouth-start.service\033[0m"
